export const cities = [
    {
      id: 61,
      name: 'London',
      country_id: 215,
      country_name: 'United Kingdom',
      country_flag_url: 'https://b.zmtcdn.com/images/countries/flags/country_215.png',
      should_experiment_with: 0,
      has_go_out_tab: 0,
      discovery_enabled: 0,
      has_new_ad_format: 0,
      is_state: 0,
      state_id: 142,
      state_name: 'England and Wales',
      state_code: 'England and Wales'
    },
    {
      id: 3454,
      name: 'London, ON',
      country_id: 37,
      country_name: 'Canada',
      country_flag_url: 'https://b.zmtcdn.com/images/countries/flags/country_37.png',
      should_experiment_with: 0,
      has_go_out_tab: 0,
      discovery_enabled: 0,
      has_new_ad_format: 0,
      is_state: 0,
      state_id: 124,
      state_name: 'Ontario',
      state_code: 'ON'
    },
    {
      id: 5836,
      name: 'London, KY',
      country_id: 216,
      country_name: 'United States',
      country_flag_url: 'https://b.zmtcdn.com/images/countries/flags/country_216.png',
      should_experiment_with: 0,
      has_go_out_tab: 0,
      discovery_enabled: 0,
      has_new_ad_format: 0,
      is_state: 0,
      state_id: 85,
      state_name: 'Kentucky',
      state_code: 'KY'
    },
    {
      id: 9824,
      name: 'Londonderry, VT',
      country_id: 216,
      country_name: 'United States',
      country_flag_url: 'https://b.zmtcdn.com/images/countries/flags/country_216.png',
      should_experiment_with: 0,
      has_go_out_tab: 0,
      discovery_enabled: 0,
      has_new_ad_format: 0,
      is_state: 0,
      state_id: 114,
      state_name: 'Vermont',
      state_code: 'VT'
    },
    {
      id: 10545,
      name: 'New London, CT',
      country_id: 216,
      country_name: 'United States',
      country_flag_url: 'https://b.zmtcdn.com/images/countries/flags/country_216.png',
      should_experiment_with: 0,
      has_go_out_tab: 0,
      discovery_enabled: 0,
      has_new_ad_format: 0,
      is_state: 0,
      state_id: 75,
      state_name: 'Connecticut',
      state_code: 'CT'
    },
    {
      id: 4949,
      name: 'New London, IA',
      country_id: 216,
      country_name: 'United States',
      country_flag_url: 'https://b.zmtcdn.com/images/countries/flags/country_216.png',
      should_experiment_with: 0,
      has_go_out_tab: 0,
      discovery_enabled: 0,
      has_new_ad_format: 0,
      is_state: 0,
      state_id: 80,
      state_name: 'Iowa',
      state_code: 'IA'
    },
    {
      id: 7543,
      name: 'New London, NH',
      country_id: 216,
      country_name: 'United States',
      country_flag_url: 'https://b.zmtcdn.com/images/countries/flags/country_216.png',
      should_experiment_with: 0,
      has_go_out_tab: 0,
      discovery_enabled: 0,
      has_new_ad_format: 0,
      is_state: 0,
      state_id: 98,
      state_name: 'New Hampshire',
      state_code: 'NH'
    },
    {
      id: 7150,
      name: 'New London, NC',
      country_id: 216,
      country_name: 'United States',
      country_flag_url: 'https://b.zmtcdn.com/images/countries/flags/country_216.png',
      should_experiment_with: 0,
      has_go_out_tab: 0,
      discovery_enabled: 0,
      has_new_ad_format: 0,
      is_state: 0,
      state_id: 95,
      state_name: 'North Carolina',
      state_code: 'NC'
    }
  ];

export const citiesResponse = {
    location_suggestions: cities,
    status: 'success',
    has_more: 0,
    has_total: 0,
    user_has_adresses: true
}
